# ingress.yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: bookclub
  name: nginx-ingress-microk8s
  labels:
    app: nginx-ingress-microk8s
  annotations:
    # kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/default-backend: service1
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: "<MY-DOMAIN.COM>"
      http:
        paths:
          - pathType: Prefix
            path: "/service1/(.*)"
            backend:
              service:
                name: service1
                port:
                  number: 80
    - host: "<MY-DOMAIN.COM>"
      http:
        paths:
          - pathType: Prefix
            path: "/service2"
            backend:
              service:
                name: service2
                port:
                  number: 80
          - pathType: Prefix
            path: "/service3/(.*)"
            backend:
              service:
                name: service3
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ingress
  namespace: ingress
spec:
  selector:
    name: nginx-ingress-microk8s
  type: LoadBalancer
  loadBalancerIP: 192.168.1.220
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
