name: Merge to master
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types: [closed]
jobs:
  publish-to-github-registry:
    name: Publish Docker image to registry
    uses: ./.github/workflows/publish-to-registry.yml
    secrets: inherit
  