name: Publish Docker image to registry
on:
  workflow_dispatch:
  workflow_call:

jobs:
  publish-to-github-registry:
    name: Publish Docker image to Github registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Prepare Docker tags for ${{ matrix.browser }} image
        id: prepare_docker_tags
        uses: L-Sypniewski/github-create-docker-tags-action@master
        env:
          IMAGE_NAME: hello-containers-arm
          ADD_LATEST_TAG: true
          PROJECT_NAME: ${{ github.repository_owner }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_REGISTRY_PAT }}
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-
      - name: Build and push Docker image for ${{ matrix.browser }}
        uses: docker/build-push-action@v3
        with:
          file: hellocontainers/Dockerfile
          context: ./hellocontainers
          push: true
          tags: latest
          platforms: linux/amd64
          labels: "org.opencontainers.image.source=https://github.com/${{ github.repository }}"
          build-args: |
            BROWSER=${{ matrix.browser }}
            BASE_IMAGE=runtime-deps
            SELF_CONTAINED=true
